---
name: Add preview link

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const repo = context.repo.owner + '/' + context.repo.repo;
            const ref = context.ref;
            const link = `https://raw.githubusercontent.com/${repo}/${ref}/src/data.json`;
            console.log(link);

